name: Jira Service Request Handler

on:
  repository_dispatch:
    types: [jira-issue-created]

jobs:
  create-github-issue-from-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Print Jira Issue Info
        run: |
          echo "Triggered by Jira issue: ${{ github.event.client_payload }}"
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
      
      - name: Create GitHub Issue from Jira Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          JIRA_ISSUE_PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: |
          python create_github_issue_from_jira.py
